# Packages to install for build to work
# execute 'make' in terminal to run this
# run this in /www folder
install:
	npm install gulp --save-dev
	npm install gulp-cached --save-dev
	npm install gulp-jshint-cached --save-dev
	npm install gulp-shell --save-dev
	npm install gulp-replace --save-dev
	npm install gulp-zip --save-dev
	npm install fs --save-dev
	npm install jshint-stylish --save-dev
